import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedppventanawidget/generated/GeneratedSubirimagendesdelanubeWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedppventanawidget/generated/GeneratedUploadToFTPWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedppventanawidget/generated/GeneratedSubirimagendesdearchivoWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedppventanawidget/generated/GeneratedUploadtotheCloudWidget.dart';

/* Frame ppventana
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPpventanaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 350.0,
        height: 361.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(178, 202, 240, 248),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedUploadToFTPWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedUploadtotheCloudWidget(),
              ),
              Positioned(
                left: 85.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 50.0,
                child: GeneratedSubirimagendesdearchivoWidget(),
              ),
              Positioned(
                left: 87.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 50.0,
                child: GeneratedSubirimagendesdelanubeWidget(),
              )
            ]),
      ),
    ));
  }
}
