import 'package:flutter/material.dart';

/* UndefinedNode OB Forms/Nombre de usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOBFormsNombredeusuarioWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
