import 'package:flutter/material.dart';

/* UndefinedNode OB Forms/Mantener sesión iniciada
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOBFormsMantenersesininiciadaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
