import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedImage8Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedFrame6Widget2.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedMenuopenWidget3.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedImage3Widget3.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedGroup1Widget3.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedNewreleasesWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedOfertasWidget4.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedparatiwidget/generated/GeneratedOfertasWidget5.dart';

/* Frame para ti
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedParatiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedImage3Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedFrame6Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 305.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedMenuopenWidget3(),
              ),
              Positioned(
                left: 9.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 63.180728912353516,
                child: GeneratedGroup1Widget3(),
              ),
              Positioned(
                left: 15.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 352.0,
                child: GeneratedOfertasWidget4(),
              ),
              Positioned(
                left: 309.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedNewreleasesWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 158.0,
                child: GeneratedOfertasWidget5(),
              ),
              Positioned(
                left: 27.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 138.0,
                child: GeneratedImage8Widget(),
              )
            ]),
      ),
    ));
  }
}
