import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedOfertasWidget2.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedMenuopenWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedOfertasWidget1.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedpaginaprincipalwidget/generated/GeneratedImage5Widget.dart';

/* Frame Pagina principal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginaprincipalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedMenuopenWidget(),
              ),
              Positioned(
                left: 9.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 63.180728912353516,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 352.0,
                child: GeneratedOfertasWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 309.0,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 158.0,
                child: GeneratedOfertasWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 522.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 300.0,
                child: GeneratedImage6Widget(),
              )
            ]),
      ),
    ));
  }
}
