import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedMenuopenWidget4.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedOfertasWidget8.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedFrame6Widget3.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedOfertasWidget7.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedImage3Widget4.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedNewreleasesWidget2.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedGroup1Widget4.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatednuevowidget2/generated/GeneratedNewreleasesWidget1.dart';

/* Frame Nuevo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNuevoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedImage3Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedFrame6Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 305.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedMenuopenWidget4(),
              ),
              Positioned(
                left: 9.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 63.180728912353516,
                child: GeneratedGroup1Widget4(),
              ),
              Positioned(
                left: 15.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 352.0,
                child: GeneratedOfertasWidget7(),
              ),
              Positioned(
                left: 15.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 158.0,
                child: GeneratedOfertasWidget8(),
              ),
              Positioned(
                left: 300.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedNewreleasesWidget1(),
              ),
              Positioned(
                left: 308.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 42.0,
                child: GeneratedNewreleasesWidget2(),
              )
            ]),
      ),
    ));
  }
}
