import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedMenuopenWidget2.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedImage3Widget2.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedFrame6Widget1.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedconfiguracionwidget1/generated/GeneratedRectangle1Widget2.dart';

/* Frame configuracion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConfiguracionWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedImage3Widget2(),
              ),
              Positioned(
                left: 69.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 33.0,
                child: GeneratedFrame6Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 33.0,
                child: GeneratedFrame7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 305.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedMenuopenWidget2(),
              ),
              Positioned(
                left: 9.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 63.180728912353516,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 33.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 270.0,
                child: GeneratedImage10Widget(),
              )
            ]),
      ),
    ));
  }
}
