import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedppwidget1/generated/GeneratedImage4Widget6.dart';

/* Frame pp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPpWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 300.0,
        height: 300.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(0, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 284.89697265625,
                height: 300.0,
                child: GeneratedImage4Widget6(),
              )
            ]),
      ),
    ));
  }
}
