import 'package:flutter/material.dart';

/* UndefinedNode OB Forms/Usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOBFormsUsuarioWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
