import 'package:flutter/material.dart';

/* UndefinedNode OB Forms/Contraseña
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOBFormsContraseaWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
