import 'package:flutter/material.dart';

/* UndefinedNode OB Forms/Estoy de acuerdo y he leído los términos y condiciones
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOBFormsEstoydeacuerdoyheledolostrminosycondicionesWidge1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
