import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedclouduploadwidget/generated/GeneratedVectorWidget28.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedclouduploadwidget/generated/GeneratedVectorWidget29.dart';

/* Frame Cloud upload
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedClouduploadWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 96.0,
        height: 96.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedVectorWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 64.0,
                child: GeneratedVectorWidget29(),
              )
            ]),
      ),
    ));
  }
}
