import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatediniciowidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatediniciowidget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatediniciowidget/generated/GeneratedFrame1Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: -9.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 317.0,
                child: GeneratedPolygon1Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 158.0,
                child: GeneratedFrame1Widget(),
              )
            ]),
      ),
    ));
  }
}
