import 'package:flutter/material.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedSecureMailWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedCalendarWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedPpWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedTusDatosWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedVerifieduserWidget.dart';
import 'package:flutterapp/rivasandrade6_i_20damovilesandroidapp/generatedperfilwidget2/generated/GeneratedMenuopenWidget1.dart';

/* Frame perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedImage3Widget1(),
              ),
              Positioned(
                left: 9.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 211.0,
                child: GeneratedTusDatosWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 311.0,
                child: GeneratedPpWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 75.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 305.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 39.0,
                child: GeneratedMenuopenWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 63.180728912353516,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 43.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedVerifieduserWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedSecureMailWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedCalendarWidget(),
              )
            ]),
      ),
    ));
  }
}
